sumocoders/FrameworkStylePackage

src/js/Framework/Flash.js

The container gives the closing button wrapping div wrong width and height values causing the button to disappear.

Remove container from alert

---

src/js/Framework/LoadingBar.js

Use the correct Bootstrap 4 classes for the loading bar in the header.

Use the correct classes for the animated loading bar

---

package-lock.json
package.json
src/js/Framework/DateTimePicker/DatePicker.js
src/js/Framework/DateTimePicker/DateTimePicker.js
src/js/Framework/DateTimePicker/TimePicker.js
src/js/Index.js

I added [tempusdominus/bootstrap-4](https://github.com/tempusdominus/bootstrap-4) and [moment.js](https://github.com/moment/moment/) as dependencies. These are then used in components responsible by displaying the date time pickers on date and time fields.
https://monosnap.com/image/BlNIGuEcPlxvHg7pjYJvQwcHkR04wV

Bootstrap 4 datepicker en plugin integratie

---

src/js/Framework/FormCollection.js

When no index is defined one should be set.

Add the collection index if not set

---

package-lock.json

* Updated the packages with a vulnerability
* Required stylelint and standard-config per default

Improve required packages

---

src/js/Framework/FormCollection.js

https://app.activecollab.com/108877/projects/533/tasks/101617

Fix double collection button that was hidden

---

src/sass/_imports.scss

Load datepicker styling by default

Load datepicker styling by default

---

src/sass/components/_cards.scss

Moet samen met https://github.com/sumocoders/FrameworkCoreBundle/pull/70 gereleased worden
Van 
Naar

Make class for a card collection

---

src/sass/_imports.scss
src/sass/components/_select2.scss
src/sass/plugins/_select2.scss

https://app.activecollab.com/108877/projects/533/tasks/124668

Load styling select2 by default and fix dark mode

---

src/sass/components/_forms.scss

https://app.activecollab.com/108877/projects/533/tasks/125354

Show custom file input errors

---

src/sass/_bootstrap-variables.scss

AC task https://app.activecollab.com/108877/projects/533/tasks/136848
Replace divisions with math.div

Remove deprecations for dart sass

---

src/js/Framework/FormCollection.js
src/js/Index.js

13e684cd37c6cb87f9adb0906128f60adb26cc3f is een fix voor: https://app.activecollab.com/108877/projects/533/tasks/146130
05a258cda7e616326c549bced7ea2e01737a3c4e is general housekeeping (opkuis + jquery wegwerken)

Fix datepickers in collections

---

package.json
src/sass/_bootstrap-variables.scss
src/sass/components/_navbar.scss
src/sass/components/_toasts.scss
src/sass/layouts/_actions.scss
src/sass/layouts/_framework.scss
src/sass/style-dark.scss

Mostly replacing old division by slash usage by wrapping it in calc()

Fix all dart-sass deprecations

---

package-lock.json
package.json
src/sass/_bootstrap-imports.scss

See https://github.com/twbs/bootstrap/issues/36785

Fix bs 5 2

---

src/js/Framework/Clipboard.js

Fix jquery reference of selecting text for copying it to clipboard

Fix clipboard

---

src/js/Framework/DateTimePicker/TimePicker.js

https://app.activecollab.com/108877/reports/assignments?modal=Task-160914-533
related to https://github.com/sumocoders/FrameworkCoreBundle/pull/112

Add event listener to clear time field

---

package-lock.json
package.json
src/js/Framework/DateTimePicker/DatePicker.js

Also see https://github.com/sumocoders/FrameworkCoreBundle/pull/114

Use bazinga Translator as a dependency instead of relying on a global

---

package-lock.json
package.json

See https://github.com/willdurand/BazingaJsTranslationBundle/blob/master/Resources/doc/index.md#installation-1

Bazinga needs intl-messageformat

---

package-lock.json
package.json

Use bootstrap 5.2.3 instead off the latest version (eg 5.3) as it breaks compilation

Use a fixed version of bootstrap 5.2.3

---

package.json

Merge with https://github.com/sumocoders/application-skeleton/pull/98

Remove bazinga-translator package

---

src/js/Framework/FormCollection.js

Adds support for a min and max data attribute to limit/setup a form collection

Add min/max to form collection

---

src/js/Framework/FormCollection.js

Don't use this. format since it isn't a class but a function

---

src/js/Framework/Clipboard.js
src/js/Framework/DateTimePicker/DateTimePicker.js
src/js/Framework/DateTimePicker/TimePicker.js
src/js/Framework/Flash.js
src/js/Framework/Sidebar.js
src/js/Framework/Theme.js

Building/compiling was not working.
It can't find the files when the extension is not included in the import statement.

Add extension

---

src/js/Framework/DateTimePicker/DatePicker.js
src/js/Framework/DateTimePicker/DateTimePicker.js
src/js/Framework/DateTimePicker/TimePicker.js

Time picking didn't show up for datetimepickers, instead of changing config after initialisation, directly set options in flatpickr

Fix time pickers
